#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Bind development pilot saves to exact gameplay inputs; never changes pilot data."""
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
RUN=ROOT/'.work/flight/run'
PROFILES=('WORLD.PAK','PILOT.DAT','NAV.DAT','APPROACH.DAT','PLAYER.DAT',
          'PROPULSE.DAT','RESOURCE.DAT','SHIELD.DAT')
GAMEPLAY=('dos/flight/navigation.c','dos/navigation/approach.c','dos/motion/motion.c',
          'dos/propulsion/propulsion.c','dos/resources/resources.c','dos/shields/shields.c',
          'dos/flight/campaign.c','dos/persistence/state.c','dos/persistence/codec.c')
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    limits=ROOT/'dos/persistence/native-limits.json'
    report=json.loads((ROOT/'dos/reports/native-persistence-contract.json').read_text())
    assert digest(limits)==report['artifact_sha256']['LIMITS.json']
    data=json.loads(limits.read_text())
    assert data['capacity']==15 and len(data['cargo_profiles'])==16
    manifest={'schema':1,'upstream':report['source_commit'],
       'scope':'Development Sol stock Sparrow; no missions, guns, jump, daily economy or native interchange.',
       'profiles':{n:digest(RUN/n) for n in PROFILES},
       'gameplay':{n:digest(ROOT/n) for n in GAMEPLAY},
       'limits_sha256':digest(limits),
       'semantics':'one-pilot-landed-v1; epoch-zero Sol; frozen calendar; port recharge; no trainer reset'}
    raw=json.dumps(manifest,sort_keys=True,separators=(',',':')).encode()
    identity=hashlib.sha256(raw).digest()
    (RUN/'SAVEKEY.json').write_bytes(raw+b'\n')
    numbers=lambda xs:','.join(format(x,'.17g') for x in xs)
    header='/* Generated by dos/persistence/assets.py; do not edit. */\n'
    header+='static const PSContext campaign_context={{'+','.join(str(b) for b in identity)+'},'
    header+=numbers([data['capacity'],data['max_crew'],data['fuel'],data['shields'],data['hull']])+'};\n'
    header+='static const int campaign_date[3]={'+numbers(data['date'])+'};\n'
    header+='static const int campaign_crew='+str(data['required_crew'])+';\n'
    header+='static const double cargo_profiles[16][7]={\n'
    header+=',\n'.join('{'+numbers(row)+'}' for row in data['cargo_profiles'])+'\n};\n'
    (RUN/'SAVEKEY.H').write_text(header)
    print('save_content_sha256='+identity.hex())
if __name__=='__main__': main()
