[sdl]
fullscreen=false
output=surface
[dosbox]
machine=svga_s3
memsize=16
[render]
frameskip=0
scaler=none
[cpu]
core=normal
cputype=pentium_slow
cycles=fixed 20000
[mixer]
nosound=true
[midi]
mpu401=none
[sblaster]
sbtype=none
[autoexec]
mount c /work/.work/dos-probe
c:
CWSDPMI -s-
RUNTIME.EXE > RUNTIME.TXT
exit
